/**
 * Playlist dataset service.
 *
 * Loads the pre-built dataset in `public/playlist-data.json` (generated by
 * `scripts/convert-playlists.cjs` from public playlist datasets) and exposes
 * query helpers used for homepage sections, search, recommendations and as an
 * offline / API-failure fallback.
 *
 * The file uses a compact wire format (v2) where artist names and track rows
 * are deduped; this module expands it once into memory.
 */

export interface DatasetTrack {
  id: string;
  artist: string;
  track: string;
}

export interface DatasetPlaylist {
  id: string;
  title: string;
  category: string;
  description?: string;
  source: string;
  tracks: DatasetTrack[];
}

export interface DatasetArtist {
  id: string;
  name: string;
  count: number;
}

interface CompactData {
  v: number;
  generatedAt: string;
  artists: string[];
  tracks: [number, string][];
  playlists: { t: string; c: string; d?: string; s: string; k: number[] }[];
}

interface ExpandedData {
  playlists: DatasetPlaylist[];
  tracks: DatasetTrack[];
  artists: DatasetArtist[];
  /** lowercased "artist|track" -> track */
  trackByKey: Map<string, DatasetTrack>;
  /** lowercased artist -> playlists containing them */
  playlistsByArtist: Map<string, DatasetPlaylist[]>;
  generatedAt: string;
}

const DATA_URL = "/playlist-data.json";

let cache: ExpandedData | null = null;
let inflight: Promise<ExpandedData> | null = null;

function expand(raw: CompactData): ExpandedData {
  const tracks: DatasetTrack[] = raw.tracks.map(([artistIdx, title], i) => ({
    id: `tr_${i}`,
    artist: raw.artists[artistIdx] ?? "Unknown Artist",
    track: title,
  }));

  const artistCounts = new Map<string, number>();
  const trackByKey = new Map<string, DatasetTrack>();
  for (const t of tracks) {
    trackByKey.set(`${t.artist.toLowerCase()}|${t.track.toLowerCase()}`, t);
  }

  const playlists: DatasetPlaylist[] = raw.playlists.map((p, i) => ({
    id: `pl_${i}`,
    title: p.t,
    category: p.c,
    description: p.d,
    source: p.s,
    tracks: p.k.map((idx) => tracks[idx]).filter(Boolean),
  }));

  const playlistsByArtist = new Map<string, DatasetPlaylist[]>();
  for (const pl of playlists) {
    const seen = new Set<string>();
    for (const t of pl.tracks) {
      const key = t.artist.toLowerCase();
      artistCounts.set(key, (artistCounts.get(key) ?? 0) + 1);
      if (seen.has(key)) continue;
      seen.add(key);
      if (!playlistsByArtist.has(key)) playlistsByArtist.set(key, []);
      playlistsByArtist.get(key)!.push(pl);
    }
  }

  const artists: DatasetArtist[] = Array.from(artistCounts.entries())
    .map(([key, count], i) => ({
      id: `ar_${i}`,
      name: tracks.find((t) => t.artist.toLowerCase() === key)?.artist ?? key,
      count,
    }))
    .sort((a, b) => b.count - a.count);

  return { playlists, tracks, artists, trackByKey, playlistsByArtist, generatedAt: raw.generatedAt };
}

/** Loads (once) and returns the expanded dataset. */
export async function ensurePlaylistData(): Promise<ExpandedData> {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = fetch(DATA_URL, { cache: "force-cache" })
    .then((r) => {
      if (!r.ok) throw new Error(`playlist dataset ${r.status}`);
      return r.json() as Promise<CompactData>;
    })
    .then((raw) => {
      cache = expand(raw);
      return cache;
    })
    .catch((err) => {
      inflight = null;
      throw err;
    });
  return inflight;
}

/** Synchronous accessor — null until `ensurePlaylistData()` resolves. */
export function getLoadedPlaylistData(): ExpandedData | null {
  return cache;
}

/** Kicks off loading without awaiting (safe to call repeatedly). */
export function preloadPlaylistData(): void {
  ensurePlaylistData().catch(() => {});
}

const MOOD_KEYWORDS: Record<string, string[]> = {
  chill: ["chill", "relax", "calm", "ambient", "lo-fi", "lofi", "acoustic", "unwind"],
  workout: ["workout", "gym", "fitness", "running", "exercise", "pump", "energy"],
  party: ["party", "dance", "club", "hits", "banger", "rave"],
  focus: ["focus", "study", "concentrate", "instrumental", "classical", "piano"],
  sad: ["sad", "melancholy", "heartbreak", "emotional", "slow", "blues"],
  happy: ["happy", "upbeat", "positive", "feel good", "feel-good", "summer"],
  sleep: ["sleep", "ambience", "ambient", "night", "calm"],
  romance: ["love", "romance", "sensual", "slow jam", "r&b"],
};

function matchesKeywords(text: string, keywords: string[]): boolean {
  const lower = text.toLowerCase();
  return keywords.some((kw) => lower.includes(kw));
}

export async function getPlaylistsByGenre(genre: string, limit = 20): Promise<DatasetPlaylist[]> {
  const { playlists } = await ensurePlaylistData();
  const keywords = genre.toLowerCase().split(/[\s/&]+/).filter((k) => k.length > 2);
  if (!keywords.length) return [];
  return playlists
    .filter((pl) => matchesKeywords(`${pl.title} ${pl.category}`, keywords))
    .slice(0, limit);
}

export async function getPlaylistsByMood(mood: string, limit = 20): Promise<DatasetPlaylist[]> {
  const { playlists } = await ensurePlaylistData();
  const keywords = MOOD_KEYWORDS[mood.toLowerCase()] ?? [mood.toLowerCase()];
  return playlists
    .filter((pl) => matchesKeywords(`${pl.title} ${pl.category} ${pl.description ?? ""}`, keywords))
    .slice(0, limit);
}

export async function searchDatasetTracks(query: string, limit = 50): Promise<DatasetTrack[]> {
  const { tracks } = await ensurePlaylistData();
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  const starts: DatasetTrack[] = [];
  const contains: DatasetTrack[] = [];
  for (const t of tracks) {
    const title = t.track.toLowerCase();
    const artist = t.artist.toLowerCase();
    if (title.startsWith(q) || artist.startsWith(q)) starts.push(t);
    else if (title.includes(q) || artist.includes(q)) contains.push(t);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}

export async function searchDatasetPlaylists(query: string, limit = 20): Promise<DatasetPlaylist[]> {
  const { playlists } = await ensurePlaylistData();
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  return playlists
    .filter((pl) => pl.title.toLowerCase().includes(q) || pl.category.toLowerCase().includes(q))
    .slice(0, limit);
}

export async function searchDatasetArtists(query: string, limit = 20): Promise<DatasetArtist[]> {
  const { artists } = await ensurePlaylistData();
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  return artists.filter((a) => a.name.toLowerCase().includes(q)).slice(0, limit);
}

export async function getPopularPlaylists(limit = 10): Promise<DatasetPlaylist[]> {
  const { playlists } = await ensurePlaylistData();
  return playlists.slice(0, limit); // dataset is pre-sorted by track count
}

export async function getRandomPlaylist(): Promise<DatasetPlaylist | null> {
  const { playlists } = await ensurePlaylistData();
  if (!playlists.length) return null;
  return playlists[Math.floor(Math.random() * playlists.length)];
}

export async function getRandomPlaylists(count = 5): Promise<DatasetPlaylist[]> {
  const { playlists } = await ensurePlaylistData();
  const out: DatasetPlaylist[] = [];
  const used = new Set<number>();
  while (out.length < Math.min(count, playlists.length)) {
    const i = Math.floor(Math.random() * playlists.length);
    if (used.has(i)) continue;
    used.add(i);
    out.push(playlists[i]);
  }
  return out;
}

export async function getTopDatasetArtists(limit = 30): Promise<DatasetArtist[]> {
  const { artists } = await ensurePlaylistData();
  return artists.slice(0, limit);
}

export async function getPlaylistsForArtist(artist: string, limit = 10): Promise<DatasetPlaylist[]> {
  const { playlistsByArtist } = await ensurePlaylistData();
  return (playlistsByArtist.get(artist.toLowerCase()) ?? []).slice(0, limit);
}

export async function getPlaylistById(id: string): Promise<DatasetPlaylist | null> {
  const { playlists } = await ensurePlaylistData();
  return playlists.find((p) => p.id === id) ?? null;
}

export const MOOD_KEYS = Object.keys(MOOD_KEYWORDS);
