import type { Track, Artist } from "@/data/mockData";
import type { Album } from "@/components/cards/AlbumCard";

/**
 * Search cache — every completed search (results + metadata) is stored per
 * query so search history opens instantly and works offline. Also holds the
 * artist blocklist used to keep unwanted artists out of results.
 */

const CACHE_KEY = "routenet_search_cache_v1";
const MAX_ENTRIES = 30;
const TTL = 1000 * 60 * 60 * 24 * 7; // a week

export interface CachedSearch {
  query: string;
  ts: number;
  tracks: Track[];
  artists: Artist[];
  albums: Album[];
}

type CacheShape = Record<string, CachedSearch>;

function readAll(): CacheShape {
  try { return JSON.parse(localStorage.getItem(CACHE_KEY) || "{}") as CacheShape; } catch { return {}; }
}

function writeAll(data: CacheShape) {
  try { localStorage.setItem(CACHE_KEY, JSON.stringify(data)); } catch { /* quota */ }
}

const key = (q: string) => q.trim().toLowerCase();

export function readSearchCache(query: string): CachedSearch | null {
  if (!query.trim()) return null;
  const entry = readAll()[key(query)];
  if (!entry) return null;
  if (Date.now() - entry.ts > TTL) return null;
  return entry;
}

export function writeSearchCache(query: string, payload: Omit<CachedSearch, "query" | "ts">) {
  if (!query.trim()) return;
  const all = readAll();
  all[key(query)] = {
    query: query.trim(),
    ts: Date.now(),
    tracks: payload.tracks.slice(0, 40),
    artists: payload.artists.slice(0, 20),
    albums: payload.albums.slice(0, 20),
  };
  const entries = Object.entries(all).sort((a, b) => b[1].ts - a[1].ts).slice(0, MAX_ENTRIES);
  writeAll(Object.fromEntries(entries));
}

export function clearSearchCache() {
  try { localStorage.removeItem(CACHE_KEY); } catch { /* ignore */ }
}

/* ---------------------------- artist blocklist ---------------------------- */

const BLOCK_KEY = "routenet_blocked_artists_v1";

/** Channel-style / placeholder "artists" that should never appear in results. */
const DEFAULT_BLOCKED = [
  "various artists", "unknown artist", "topic", "auto-generated by youtube",
  "karaoke", "cover band", "tribute band", "lyrics", "vevo",
];

export function getBlockedArtists(): string[] {
  try {
    const custom = JSON.parse(localStorage.getItem(BLOCK_KEY) || "[]") as string[];
    return Array.from(new Set([...DEFAULT_BLOCKED, ...custom.map((a) => a.toLowerCase())]));
  } catch { return DEFAULT_BLOCKED; }
}

export function blockArtist(name: string) {
  if (!name.trim()) return;
  try {
    const custom = JSON.parse(localStorage.getItem(BLOCK_KEY) || "[]") as string[];
    const next = Array.from(new Set([...custom, name.trim().toLowerCase()]));
    localStorage.setItem(BLOCK_KEY, JSON.stringify(next));
  } catch { /* ignore */ }
}

export function unblockArtist(name: string) {
  try {
    const custom = JSON.parse(localStorage.getItem(BLOCK_KEY) || "[]") as string[];
    localStorage.setItem(BLOCK_KEY, JSON.stringify(custom.filter((a) => a !== name.trim().toLowerCase())));
  } catch { /* ignore */ }
}

/** True when this artist / channel name is blocked from search results. */
export function isBlockedArtist(name?: string, blocked = getBlockedArtists()): boolean {
  const n = (name || "").toLowerCase().trim();
  if (!n) return false;
  return blocked.some((b) => n === b || n.includes(b));
}
