// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jixcwwvaqxsvjqtqqjrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeGN3d3ZhcXhzdmpxdHFxanJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzMjk0NDgsImV4cCI6MjEwMDkwNTQ0OH0.a_fmrsY-sQpsu5tMdh33sQDxrhwKmW2JEn0E60PVfh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});